<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <material name="orange">
        <color rgba="1 0.5 0.0 1" />
    </material>
    <material name="yellow">
        <color rgba="1 0.8 0 1" />
    </material>
    
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_length" value="0.3" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="0.5" l="${2*arm_base_length}" w="${2*arm_base_width}" h="${2*arm_base_height}" xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
    </link> 


    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*forearm_radius}" h="${2*forearm_length}" xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0"/>
    </link> 

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*forearm_radius}" h="${2*forearm_length}" xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0"/>
    </link> 
 
    

    <joint name="base_arm_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link" />
        <origin xyz="${base_length/4.0} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <limit lower="0.0" upper="${pi/2.0}" effort="100" velocity="100"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
        <dynamics damping="0.1" friction="0.05"/>
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
        <dynamics damping="0.1" friction="0.05"/>
    </joint>

</robot>